---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install packages
        run: |
          pip install -U \
            autopep8 flake8 flake8-bugbear flake8-isort pep8-naming .
      - name: Validate the codes using flake8
        run: |
          find . -name '*.py' | xargs flake8
      - name: Test commands
        run: |
          set -x
          pdbio --version
          pdbio vcf2csv --sort --tsv test/example.vcf
          pdbio vcf2csv --expand-info --expand-samples test/example.vcf
          pdbio vcfsort test/example.vcf
          pdbio bed2csv --sort --tsv test/example.bed
          pdbio bed2csv test/example.bed /tmp/example.bed.csv
          cat /tmp/example.bed.csv
          pdbio bedsort test/example.bed
          pdbio sam2csv --sort --tsv test/example.sam
          pdbio sam2csv test/example.sam
          pdbio samsort test/example.sam /tmp/example.sorted.sam
          cat /tmp/example.sorted.sam
      - name: Test a class
        run: |
          cat << EOF | python3
          from pprint import pprint
          from pdbio.vcfdataframe import VcfDataFrame
          vcf_path = 'test/example.vcf'
          vcfdf = VcfDataFrame(path=vcf_path)
          pprint(vcfdf.header)
          pprint(vcfdf.samples)
          print(vcfdf.df)
          vcfdf.sort()
          print(vcfdf.df)
          EOF
